/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.zoologicods;

import java.time.LocalTime;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author diego
 */
public class frmRegistrarItinerario extends javax.swing.JFrame {


    /**
     * Creates new form frmRegistrarItinerario
     */
    public frmRegistrarItinerario() {

    initComponents();

    }


 

  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel23 = new javax.swing.JLabel();
        btnGuarfarItinerario1 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        tfViernes1 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        tfVisitantes1 = new javax.swing.JTextField();
        cbViernes1 = new javax.swing.JCheckBox();
        tfMiercoles1 = new javax.swing.JTextField();
        cbSabado1 = new javax.swing.JCheckBox();
        jLabel26 = new javax.swing.JLabel();
        tfDuracion1 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        cbJueves1 = new javax.swing.JCheckBox();
        tfJueves1 = new javax.swing.JTextField();
        tfLongitud1 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        tfSabado1 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        cbMiercoles1 = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbLunes = new javax.swing.JCheckBox();
        jLabel15 = new javax.swing.JLabel();
        btnReiniciar = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        tfSabado = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        btnVerificar = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        tfMartes = new javax.swing.JTextField();
        cbSabado = new javax.swing.JCheckBox();
        tfDuracion = new javax.swing.JTextField();
        tfLunes = new javax.swing.JTextField();
        tfLongitud = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        cbMiercoles = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnGuarfarItinerario = new javax.swing.JButton();
        tfNombre = new javax.swing.JTextField();
        tfViernes = new javax.swing.JTextField();
        tfVisitantes = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cbViernes = new javax.swing.JCheckBox();
        tfMiercoles = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cbJueves = new javax.swing.JCheckBox();
        tfJueves = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cbMartes = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList<>();
        jLabel32 = new javax.swing.JLabel();
        btnGuarfarItinerario2 = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        tfViernes2 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        tfVisitantes2 = new javax.swing.JTextField();
        cbViernes2 = new javax.swing.JCheckBox();
        tfMiercoles2 = new javax.swing.JTextField();
        cbSabado2 = new javax.swing.JCheckBox();
        jLabel35 = new javax.swing.JLabel();
        tfDuracion2 = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        cbJueves2 = new javax.swing.JCheckBox();
        tfJueves2 = new javax.swing.JTextField();
        tfLongitud2 = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        tfSabado2 = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        cbMiercoles2 = new javax.swing.JCheckBox();
        jScrollPane5 = new javax.swing.JScrollPane();
        jList4 = new javax.swing.JList<>();

        jLabel23.setText("Visitantes (Max)");

        btnGuarfarItinerario1.setBackground(new java.awt.Color(153, 255, 153));
        btnGuarfarItinerario1.setText("Guardar Itinerario");
        btnGuarfarItinerario1.setEnabled(false);
        btnGuarfarItinerario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuarfarItinerario1ActionPerformed(evt);
            }
        });

        jLabel24.setText("Guia");

        tfViernes1.setPreferredSize(new java.awt.Dimension(70, 22));
        tfViernes1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfViernes1tfLunesKeyTyped(evt);
            }
        });

        jLabel25.setText("Guia");

        tfVisitantes1.setEnabled(false);
        tfVisitantes1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfVisitantes1KeyTyped(evt);
            }
        });

        cbViernes1.setText("Viernes");
        cbViernes1.setEnabled(false);
        cbViernes1.setPreferredSize(new java.awt.Dimension(70, 22));
        cbViernes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbViernes1ActionPerformed(evt);
            }
        });

        tfMiercoles1.setPreferredSize(new java.awt.Dimension(70, 22));
        tfMiercoles1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfMiercoles1tfLunesKeyTyped(evt);
            }
        });

        cbSabado1.setText("Sabado");
        cbSabado1.setEnabled(false);
        cbSabado1.setPreferredSize(new java.awt.Dimension(70, 22));
        cbSabado1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSabado1ActionPerformed(evt);
            }
        });

        jLabel26.setText("Hora inicial");

        tfDuracion1.setEnabled(false);
        tfDuracion1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfDuracion1KeyTyped(evt);
            }
        });

        jLabel27.setText("Longitud (M)");

        jLabel28.setText("Duración (min)");

        cbJueves1.setText("Jueves");
        cbJueves1.setEnabled(false);
        cbJueves1.setPreferredSize(new java.awt.Dimension(70, 22));
        cbJueves1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbJueves1ActionPerformed(evt);
            }
        });

        tfJueves1.setPreferredSize(new java.awt.Dimension(70, 22));
        tfJueves1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfJueves1tfLunesKeyTyped(evt);
            }
        });

        tfLongitud1.setEnabled(false);
        tfLongitud1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfLongitud1ActionPerformed(evt);
            }
        });
        tfLongitud1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfLongitud1KeyTyped(evt);
            }
        });

        jLabel29.setText("Hora inicial");

        jLabel30.setText("Hora inicial");

        tfSabado1.setPreferredSize(new java.awt.Dimension(70, 22));
        tfSabado1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfSabado1tfLunesKeyTyped(evt);
            }
        });

        jLabel31.setText("Hora inicial");

        cbMiercoles1.setText("Miercoles");
        cbMiercoles1.setEnabled(false);
        cbMiercoles1.setPreferredSize(new java.awt.Dimension(70, 22));
        cbMiercoles1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMiercoles1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 153, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton1.setBackground(new java.awt.Color(153, 255, 153));
        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Registrar Itinerario");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(jLabel21)
                .addContainerGap(185, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel21))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel11.setText("Hora inicial");

        jLabel5.setText("Longitud (M)");

        cbLunes.setText("Lunes");
        cbLunes.setEnabled(false);
        cbLunes.setPreferredSize(new java.awt.Dimension(70, 22));
        cbLunes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbLunesActionPerformed(evt);
            }
        });

        jLabel15.setText("Guia");

        btnReiniciar.setBackground(new java.awt.Color(153, 0, 51));
        btnReiniciar.setText("X");
        btnReiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReiniciarActionPerformed(evt);
            }
        });

        jLabel20.setText("Zonas Seleccionadas");

        jLabel19.setText("Hora inicial");

        tfSabado.setPreferredSize(new java.awt.Dimension(70, 22));
        tfSabado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfLunesKeyTyped(evt);
            }
        });

        jLabel18.setText("Hora inicial");

        btnVerificar.setBackground(new java.awt.Color(153, 255, 153));
        btnVerificar.setText("Verificar");
        btnVerificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerificarActionPerformed(evt);
            }
        });

        jLabel16.setText("Guia");

        jLabel17.setText("Guia");

        tfMartes.setPreferredSize(new java.awt.Dimension(70, 22));
        tfMartes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfLunesKeyTyped(evt);
            }
        });

        cbSabado.setText("Sabado");
        cbSabado.setEnabled(false);
        cbSabado.setPreferredSize(new java.awt.Dimension(70, 22));
        cbSabado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSabadoActionPerformed(evt);
            }
        });

        tfDuracion.setEnabled(false);
        tfDuracion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfDuracionKeyTyped(evt);
            }
        });

        tfLunes.setPreferredSize(new java.awt.Dimension(70, 22));
        tfLunes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfLunesKeyTyped(evt);
            }
        });

        tfLongitud.setEnabled(false);
        tfLongitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfLongitudActionPerformed(evt);
            }
        });
        tfLongitud.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfLongitudKeyTyped(evt);
            }
        });

        jLabel3.setText("Zonas Disponibles");

        jLabel8.setText("Hora inicial");

        jLabel14.setText("Guia");

        cbMiercoles.setText("Miercoles");
        cbMiercoles.setEnabled(false);
        cbMiercoles.setPreferredSize(new java.awt.Dimension(70, 22));
        cbMiercoles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMiercolesActionPerformed(evt);
            }
        });

        jLabel10.setText("Hora inicial");

        jLabel6.setText("Visitantes (Max)");

        jLabel13.setText("Guia");

        btnGuarfarItinerario.setBackground(new java.awt.Color(153, 255, 153));
        btnGuarfarItinerario.setText("Guardar Itinerario");
        btnGuarfarItinerario.setEnabled(false);
        btnGuarfarItinerario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuarfarItinerarioActionPerformed(evt);
            }
        });

        tfViernes.setPreferredSize(new java.awt.Dimension(70, 22));
        tfViernes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfLunesKeyTyped(evt);
            }
        });

        tfVisitantes.setEnabled(false);
        tfVisitantes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfVisitantesKeyTyped(evt);
            }
        });

        jLabel2.setText("Ingrese itinerario");

        cbViernes.setText("Viernes");
        cbViernes.setEnabled(false);
        cbViernes.setPreferredSize(new java.awt.Dimension(70, 22));
        cbViernes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbViernesActionPerformed(evt);
            }
        });

        tfMiercoles.setPreferredSize(new java.awt.Dimension(70, 22));
        tfMiercoles.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfLunesKeyTyped(evt);
            }
        });

        jLabel4.setText("Duración (min)");

        cbJueves.setText("Jueves");
        cbJueves.setEnabled(false);
        cbJueves.setPreferredSize(new java.awt.Dimension(70, 22));
        cbJueves.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbJuevesActionPerformed(evt);
            }
        });

        tfJueves.setPreferredSize(new java.awt.Dimension(70, 22));
        tfJueves.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfLunesKeyTyped(evt);
            }
        });

        jLabel9.setText("Hora inicial");

        jLabel7.setText("Dias de la semana");

        jLabel12.setText("Guia");

        cbMartes.setText("Martes");
        cbMartes.setEnabled(false);
        cbMartes.setPreferredSize(new java.awt.Dimension(70, 22));
        cbMartes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMartesActionPerformed(evt);
            }
        });

        jLabel1.setText("Primero Valida el itinerario");

        jLabel22.setText("para activar campos");

        jScrollPane2.setViewportView(jList1);

        jScrollPane3.setViewportView(jList2);

        jScrollPane4.setViewportView(jList3);

        jLabel32.setText("Visitantes (Max)");

        btnGuarfarItinerario2.setBackground(new java.awt.Color(153, 255, 153));
        btnGuarfarItinerario2.setText("Guardar Itinerario");
        btnGuarfarItinerario2.setEnabled(false);
        btnGuarfarItinerario2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuarfarItinerario2ActionPerformed(evt);
            }
        });

        jLabel33.setText("Guia");

        tfViernes2.setPreferredSize(new java.awt.Dimension(70, 22));
        tfViernes2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfViernes2tfLunesKeyTyped(evt);
            }
        });

        jLabel34.setText("Guia");

        tfVisitantes2.setEnabled(false);
        tfVisitantes2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfVisitantes2KeyTyped(evt);
            }
        });

        cbViernes2.setText("Viernes");
        cbViernes2.setEnabled(false);
        cbViernes2.setPreferredSize(new java.awt.Dimension(70, 22));
        cbViernes2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbViernes2ActionPerformed(evt);
            }
        });

        tfMiercoles2.setPreferredSize(new java.awt.Dimension(70, 22));
        tfMiercoles2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfMiercoles2tfLunesKeyTyped(evt);
            }
        });

        cbSabado2.setText("Sabado");
        cbSabado2.setEnabled(false);
        cbSabado2.setPreferredSize(new java.awt.Dimension(70, 22));
        cbSabado2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSabado2ActionPerformed(evt);
            }
        });

        jLabel35.setText("Hora inicial");

        tfDuracion2.setEnabled(false);
        tfDuracion2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfDuracion2KeyTyped(evt);
            }
        });

        jLabel36.setText("Longitud (M)");

        jLabel37.setText("Duración (min)");

        cbJueves2.setText("Jueves");
        cbJueves2.setEnabled(false);
        cbJueves2.setPreferredSize(new java.awt.Dimension(70, 22));
        cbJueves2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbJueves2ActionPerformed(evt);
            }
        });

        tfJueves2.setPreferredSize(new java.awt.Dimension(70, 22));
        tfJueves2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfJueves2tfLunesKeyTyped(evt);
            }
        });

        tfLongitud2.setEnabled(false);
        tfLongitud2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfLongitud2ActionPerformed(evt);
            }
        });
        tfLongitud2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfLongitud2KeyTyped(evt);
            }
        });

        jLabel38.setText("Hora inicial");

        jLabel39.setText("Hora inicial");

        tfSabado2.setPreferredSize(new java.awt.Dimension(70, 22));
        tfSabado2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfSabado2tfLunesKeyTyped(evt);
            }
        });

        jLabel40.setText("Hora inicial");

        cbMiercoles2.setText("Miercoles");
        cbMiercoles2.setEnabled(false);
        cbMiercoles2.setPreferredSize(new java.awt.Dimension(70, 22));
        cbMiercoles2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMiercoles2ActionPerformed(evt);
            }
        });

        jScrollPane5.setViewportView(jList4);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel2))
                    .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(btnVerificar)
                .addGap(12, 12, 12)
                .addComponent(btnReiniciar)
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel22))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(jLabel7))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(cbLunes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110)
                .addComponent(cbMartes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel3)
                .addGap(31, 31, 31)
                .addComponent(jLabel20))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel10))
                    .addComponent(tfLunes, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel15)))
                .addGap(110, 110, 110)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(tfMartes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel14)))
                .addGap(24, 24, 24)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(461, 461, 461)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel37)
                    .addComponent(jLabel4)))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(451, 451, 451)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfDuracion2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbMiercoles, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbMiercoles2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel35)
                            .addComponent(jLabel11))))
                .addGap(100, 100, 100)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbJueves2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbJueves, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel38))
                .addGap(80, 80, 80)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel36)
                    .addComponent(jLabel5)
                    .addComponent(tfLongitud2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfLongitud, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel32)
                    .addComponent(tfVisitantes, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfVisitantes2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfMiercoles, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfMiercoles2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel34))))
                .addGap(106, 106, 106)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfJueves, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfJueves2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel33)
                            .addComponent(jLabel16))))
                .addGap(110, 110, 110)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGuarfarItinerario)
                    .addComponent(btnGuarfarItinerario2)))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbViernes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbViernes2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(120, 120, 120)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbSabado2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbSabado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel39)
                    .addComponent(jLabel19))
                .addGap(120, 120, 120)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel40)
                    .addComponent(jLabel18)))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfViernes, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfViernes2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(100, 100, 100)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfSabado2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfSabado, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jLabel13)
                .addGap(166, 166, 166)
                .addComponent(jLabel12))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(4, 4, 4)
                        .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(btnVerificar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(btnReiniciar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel1)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel22)))
                .addGap(6, 6, 6)
                .addComponent(jLabel7)
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel20)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbLunes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbMartes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(14, 14, 14)
                                .addComponent(tfLunes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)
                                .addComponent(jLabel15))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(14, 14, 14)
                                .addComponent(tfMartes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)
                                .addComponent(jLabel14)))))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel37)
                    .addComponent(jLabel4))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfDuracion2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbMiercoles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbMiercoles2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel35)
                            .addComponent(jLabel11)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbJueves2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbJueves, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel38)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel36)
                            .addComponent(jLabel5))
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfLongitud2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfLongitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel32))
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfVisitantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfVisitantes2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfMiercoles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfMiercoles2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel34)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfJueves, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfJueves2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel33)
                            .addComponent(jLabel16)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnGuarfarItinerario)
                            .addComponent(btnGuarfarItinerario2))))
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbViernes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbViernes2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbSabado2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbSabado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel39)
                    .addComponent(jLabel19)
                    .addComponent(jLabel40)
                    .addComponent(jLabel18))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfViernes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfViernes2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfSabado2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfSabado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerificarActionPerformed

    }//GEN-LAST:event_btnVerificarActionPerformed

    private void cbViernesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbViernesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbViernesActionPerformed

    private void cbLunesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbLunesActionPerformed
       
    }//GEN-LAST:event_cbLunesActionPerformed

    private void cbMartesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMartesActionPerformed
          // TODO add your handling code here:
    }//GEN-LAST:event_cbMartesActionPerformed

    private void cbMiercolesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMiercolesActionPerformed
            // TODO add your handling code here:
    }//GEN-LAST:event_cbMiercolesActionPerformed

    private void cbJuevesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbJuevesActionPerformed
              // TODO add your handling code here:
    }//GEN-LAST:event_cbJuevesActionPerformed

    private void cbSabadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSabadoActionPerformed
      // TODO add your handling code here:
    }//GEN-LAST:event_cbSabadoActionPerformed

    private void tfLunesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfLunesKeyTyped
  
    }//GEN-LAST:event_tfLunesKeyTyped

    private void tfLongitudKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfLongitudKeyTyped

    }//GEN-LAST:event_tfLongitudKeyTyped

    private void tfLongitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfLongitudActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfLongitudActionPerformed

    private void tfVisitantesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfVisitantesKeyTyped

    }//GEN-LAST:event_tfVisitantesKeyTyped

    private void tfDuracionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfDuracionKeyTyped

    }//GEN-LAST:event_tfDuracionKeyTyped

    private void btnReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReiniciarActionPerformed
        
 
    }//GEN-LAST:event_btnReiniciarActionPerformed

    private void btnGuarfarItinerarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuarfarItinerarioActionPerformed

    }//GEN-LAST:event_btnGuarfarItinerarioActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      frmMenu f = new frmMenu();
        f.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnGuarfarItinerario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuarfarItinerario1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuarfarItinerario1ActionPerformed

    private void tfViernes1tfLunesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfViernes1tfLunesKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tfViernes1tfLunesKeyTyped

    private void tfVisitantes1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfVisitantes1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tfVisitantes1KeyTyped

    private void cbViernes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbViernes1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbViernes1ActionPerformed

    private void tfMiercoles1tfLunesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfMiercoles1tfLunesKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tfMiercoles1tfLunesKeyTyped

    private void cbSabado1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSabado1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbSabado1ActionPerformed

    private void tfDuracion1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfDuracion1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDuracion1KeyTyped

    private void cbJueves1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbJueves1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbJueves1ActionPerformed

    private void tfJueves1tfLunesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfJueves1tfLunesKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tfJueves1tfLunesKeyTyped

    private void tfLongitud1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfLongitud1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfLongitud1ActionPerformed

    private void tfLongitud1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfLongitud1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tfLongitud1KeyTyped

    private void tfSabado1tfLunesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfSabado1tfLunesKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSabado1tfLunesKeyTyped

    private void cbMiercoles1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMiercoles1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMiercoles1ActionPerformed

    private void btnGuarfarItinerario2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuarfarItinerario2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuarfarItinerario2ActionPerformed

    private void tfViernes2tfLunesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfViernes2tfLunesKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tfViernes2tfLunesKeyTyped

    private void tfVisitantes2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfVisitantes2KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tfVisitantes2KeyTyped

    private void cbViernes2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbViernes2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbViernes2ActionPerformed

    private void tfMiercoles2tfLunesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfMiercoles2tfLunesKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tfMiercoles2tfLunesKeyTyped

    private void cbSabado2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSabado2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbSabado2ActionPerformed

    private void tfDuracion2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfDuracion2KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDuracion2KeyTyped

    private void cbJueves2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbJueves2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbJueves2ActionPerformed

    private void tfJueves2tfLunesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfJueves2tfLunesKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tfJueves2tfLunesKeyTyped

    private void tfLongitud2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfLongitud2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfLongitud2ActionPerformed

    private void tfLongitud2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfLongitud2KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tfLongitud2KeyTyped

    private void tfSabado2tfLunesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfSabado2tfLunesKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSabado2tfLunesKeyTyped

    private void cbMiercoles2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMiercoles2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMiercoles2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuarfarItinerario;
    private javax.swing.JButton btnGuarfarItinerario1;
    private javax.swing.JButton btnGuarfarItinerario2;
    private javax.swing.JButton btnReiniciar;
    private javax.swing.JButton btnVerificar;
    private javax.swing.JCheckBox cbJueves;
    private javax.swing.JCheckBox cbJueves1;
    private javax.swing.JCheckBox cbJueves2;
    private javax.swing.JCheckBox cbLunes;
    private javax.swing.JCheckBox cbMartes;
    private javax.swing.JCheckBox cbMiercoles;
    private javax.swing.JCheckBox cbMiercoles1;
    private javax.swing.JCheckBox cbMiercoles2;
    private javax.swing.JCheckBox cbSabado;
    private javax.swing.JCheckBox cbSabado1;
    private javax.swing.JCheckBox cbSabado2;
    private javax.swing.JCheckBox cbViernes;
    private javax.swing.JCheckBox cbViernes1;
    private javax.swing.JCheckBox cbViernes2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JList<String> jList3;
    private javax.swing.JList<String> jList4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField tfDuracion;
    private javax.swing.JTextField tfDuracion1;
    private javax.swing.JTextField tfDuracion2;
    private javax.swing.JTextField tfJueves;
    private javax.swing.JTextField tfJueves1;
    private javax.swing.JTextField tfJueves2;
    private javax.swing.JTextField tfLongitud;
    private javax.swing.JTextField tfLongitud1;
    private javax.swing.JTextField tfLongitud2;
    private javax.swing.JTextField tfLunes;
    private javax.swing.JTextField tfMartes;
    private javax.swing.JTextField tfMiercoles;
    private javax.swing.JTextField tfMiercoles1;
    private javax.swing.JTextField tfMiercoles2;
    private javax.swing.JTextField tfNombre;
    private javax.swing.JTextField tfSabado;
    private javax.swing.JTextField tfSabado1;
    private javax.swing.JTextField tfSabado2;
    private javax.swing.JTextField tfViernes;
    private javax.swing.JTextField tfViernes1;
    private javax.swing.JTextField tfViernes2;
    private javax.swing.JTextField tfVisitantes;
    private javax.swing.JTextField tfVisitantes1;
    private javax.swing.JTextField tfVisitantes2;
    // End of variables declaration//GEN-END:variables
}
